### ISSUE TITLE
Build problems TTF2CXF_STREAM

### ISSUE THREAD

**Issue by mkarliner** [stephenhouser/f-engrave#11]
Trying a build on Catalina with a virtualenv using 3.9.4 ( and changing version in the build script)
I get:
Build macOS Application Bundle...
make: *** No rule to make target `osx'.  Stop.

*** ERROR: Failed to build TTF2CXF_STREAM ***

**Comment by warhsn** [comment]
Im getting the exact same thing on my side.

```
Build macOS Application Bundle...
make: *** No rule to make target `osx'.  Stop.

*** ERROR: Failed to build TTF2CXF_STREAM ***
```

Mac OSX 11.6 (20G165)

**Comment by warhsn** [comment]
I actually managed to get this solved. I had run the build script which failed. Then i tried the update script and this is when things went wrong. I ended up recloning the repo and it went away.

As an additional note it seems as though my pyenv was not set up correctly.
