### ISSUE TITLE
Issue installing FEngrave stating cannot install Python 3.9.1

### ISSUE THREAD

**Issue by Slaphead007** [stephenhouser/f-engrave#12]
I am trying to install the latest release of FEngrave for MacOS (1.73.1) however keep getting the error stating that it failed to install Python 3.9.1.  I have tried manually installing Python 3.9 and 3.10 but I still get the same error. 
I am installing on a MacBook Air with Monterey version 12.2.1.

**Comment by stephenhouser** [comment]
Remove the `.python-version` file. This file is used by `pyenv` to "lock" the build to a specific Python version. I have removed that file in the most recent commit to avoid future problems.
