### ISSUE TITLE
Apple Silicon version?

### ISSUE THREAD

**Issue by michaelrommel** [stephenhouser/f-engrave#13]
Hi,

has anyone ever successfully build this on Apple Silicon? I can successfully build it, and it runs, but there is only a black window with a few controls and no text can be read at all. This happens with the patched version when I recompile it and even if I take the latest 1.75 version, manually apply the patches.

The dmg version does not run, because the bundled ttf2cxs binary needs a dylib with the old x86 architecture. And since the program now no longer searches the path, it cannot find a self compiled ARM version of this program or potrace.

Thanks for any hint, what I might have to do in order to have text displayed properly with TK.

  Michael.

**Comment by mark-hoy** [comment]
I also got it running on my M1 MacMini, I don't remember all the steps though. In addition, I had the black text, it was readable when highlighted, so I did manage to get it to run. I didn't end up trying the file on my cnc as it was rough on getting setting done with black on black.

**Comment by stephenhouser** [comment]
Yea, I got an M1 (M2 actually) mac just recently and it's not working for me. Having problems with `tkinter`. Will take a look as I have time.

**Comment by stephenhouser** [comment]
Are you running dark-mode or auto and working after dark?

The straight `f-engrave.py` with no modifications on my M2 mac mini has some black on black when in dark mode, but looks proper in light-mode. Not sure if `tk` supports dark mode and suspect that to be part of the problem.

**Comment by stephenhouser** [comment]
See if this (test) version works on your Apple Silicon.

[F-Engrave-1.75-apple-silicon.dmg.zip](https://github.com/stephenhouser/f-engrave/files/13855348/F-Engrave-1.75-apple-silicon.dmg.zip)

**Comment by michaelrommel** [comment]
Wow, on a first glance, this works now and it even has now the Font list populated properly. Will test this today after work hours.
Ironically I switched the Mac to Light mode manually earlier, when I was testing F-engrave and at that time it did not work either, but I do not know, what I did wrong then, if it works now. Would you be able to share the diff to the 1.75 version, so that I can see , what modifications you additionally made to the tk setup? I know python, but I have no idea about `tk`, unfortunately...

Many thanks for the quick response and the patched version! I sincerely appreciate that!

**Comment by michaelrommel** [comment]
I tested it now and I found two things that could be improved, but now that I understand that I can work with it in Light mode, they are no big deal. The main thing is, that now the fonts are there...

1. In the Settings dialog, if I click on Save, it says it cannot open the file ~/Documents/config.ngc, but that file is not existing and it should be created. 
2. The colors are a bit weird in dark mode, making it hard to read the GUI. Screenshot attached.

But thanks a lot for this version, if you provide the patch, I can probably work from there...

<img width="937" alt="image" src="https://github.com/stephenhouser/f-engrave/assets/919935/f614917e-3255-43f3-9650-de34f1cbacbf">

**Comment by stephenhouser** [comment]
I'll work on getting this repo updated with the 1.75 patches. It might be in a separate branch as I'm not sure the effect compiling for Apple silicon will have on older macs. Or alternatively perhaps the version for older macs will live in a branch. Need to put my thinking cap on for this one.

**Comment by stephenhouser** [comment]
@michaelrommel I've updated to `v1.75` on the releases page. Let me know if it works for you. All the updates and patches are in the `master` branch.

**Comment by michaelrommel** [comment]
Thank you for providing this! I am switching to Light Mode temporarily while using the app for now!
