### ISSUE TITLE
Apple ARM Pre-Release font colors

### ISSUE THREAD

**Issue by mark-hoy** [stephenhouser/f-engrave#14]
On the plus side, the pre-release loaded without issue on my M2 Macbook Air. So thanks very much !

However, I appear to have white on white lettering,  it's white letters on a yellow back ground on a selected box. IF I highlight the box with my cursor, I can get a dark background with light lettering showing up, but it's a royal pain to view all the settings.

<img width="779" alt="Screenshot 2024-01-08 at 3 42 33 PM" src="https://github.com/stephenhouser/f-engrave/assets/42656900/2dbfd33d-e667-4bf9-9dda-59d9c656de06">

**Comment by stephenhouser** [comment]
Does this happen in "light mode" as well?

**Comment by mark-hoy** [comment]
I hadn't thought to try that when I was last messing with F-engrave. Switching to "light mode" works perfectly. 

<img width="780" alt="Screenshot 2024-01-08 at 3 54 38 PM" src="https://github.com/stephenhouser/f-engrave/assets/42656900/83a5bfcd-86e6-4e27-ae01-8adeaaaba539">

**Comment by mark-hoy** [comment]
Perhaps close this is as an issue as there is a perfect work around, just don't run dark mode.

**Comment by stephenhouser** [comment]
Perhaps just note in the top-level README. Adapting to light/dark looks to be doable but would involve more complexity than I'm currently willing to add as it would start to vary too far from Scorch's original.

For my future self or anyone else who comes looking: Changing light/dark is easy, but detecting what mode the computer is in, and when it suddenly changes, is the hard part.

Somewhere around line 9342 after `root = Tk()`:
* for dark mode add `root.configure(bg="black")`
* for light mode add `root.configure(bg="white")` which is the default.

**Comment by mark-hoy** [comment]
Seems totally reasonable to me.
