### ISSUE TITLE
Arm v1.75 pre-release: save settings to file works, reading doesn't allow selection

### ISSUE THREAD

**Issue by mark-hoy** [stephenhouser/f-engrave#15]
You can easily save the settings to "text.txt" and a file is created
➜  ~ ls -lt text.txt
-rw-r--r--@ 1 mark  staff  2567 Jan  8 15:43 text.txt

However, you can't load the configuration file as the selection of "text.txt" isn't selectable.
<img width="1005" alt="Screenshot 2024-01-08 at 4 03 55 PM" src="https://github.com/stephenhouser/f-engrave/assets/42656900/6c2c8f7e-e04b-4e25-aca5-2b3ed9acbe83">

**Comment by stephenhouser** [comment]
Click on `Show Options` and set the Filter to `All Files (*)`
<img width="429" alt="Screenshot 2024-01-08 at 7 41 17 PM" src="https://github.com/stephenhouser/f-engrave/assets/1867488/537c186f-33a3-4579-b8fd-c3ccd4b5af43">

<img width="449" alt="Screenshot 2024-01-08 at 7 41 27 PM" src="https://github.com/stephenhouser/f-engrave/assets/1867488/a0468aef-e010-41fe-81ef-c33c32df96e4">

**Comment by mark-hoy** [comment]
Ah, I see that now. The default filter seems to be a *.ngc while a saved configuration file appends a .txt  Maybe the saved file should be XXX.ngc to match up with the configuration file filter.

<img width="662" alt="Screenshot 2024-01-08 at 5 31 31 PM" src="https://github.com/stephenhouser/f-engrave/assets/42656900/2e297b54-c212-4904-bec2-8cbe0e2734eb">

**Comment by stephenhouser** [comment]
This is an upstream choice in [F-Engrave](https://www.scorchworks.com/Fengrave/fengrave.html). The `save settings` by default saves as a `.txt` file, where `read settings` prompts for an `.ngc` file, but allows for `All Files`. Changing this behaviour would be Scorch's decision.

Closing this as we have a simple workaround that does not involve diverging from Scorch's upstream version.
