### ISSUE TITLE
Fonts will not link cant get F-engrave 1.73 to run on Ventura x-86.

### ISSUE THREAD

**Issue by brookmw** [stephenhouser/f-engrave#16]
I cant get F-engrave 1.73 to run on Ventura x-86. I cant cope with Unix or the code. I read thru the documentation twice, downloaded the source and looked at the documentation within. Unfortunately, it only makes sense to a programmer!!
I am not a programmer!!
I ran the .dmg and installed without incident.
The problem I found is that when trying to make a setup file, I navigated to /system/library/fonts, where there are lots of .tff files, but the program refused to find and link to them. I tried other directories with .tff fonts within, no luck.
I made my own directory and stuck a font in it, No joy! The files should be put in the window on the setup page. Nothing is there. I cant get past it.

**Comment by stephenhouser** [comment]
Looks like 1.75+ needs to be compiled for x86 in addition to arm (apple silicon). Will work towards this along with the 1.76 update from [Scorch's original](https://www.scorchworks.com/Fengrave/fengrave.html)

**Comment by stephenhouser** [comment]
Please try the latest 1.75 release and make sure to download the `x86_64` version.

**Comment by stephenhouser** [comment]
Closing with no comment from original poster, please reopen if problem persists.
