### ISSUE TITLE
error running build.sh

### ISSUE THREAD

**Issue by zencuke** [stephenhouser/f-engrave#2]
*** creating application bundle: f-engrave ***
error: [Errno 1] Operation not permitted: '/Users/smorris/Dropbox/github/f-engrave/dist/f-engrave.app/Contents/MacOS/f-engrave'
chmod: dist/f-engrave.app/Contents/Resources/ttf2cxf_stream: No such file or directory

**Comment by zencuke** [comment]
Oops. I forgot. OS 10.13.4, High Sierra. I didn't see any errors earlier in build.sh output stream but there was a lot of output so I could have missed it.

**Comment by zencuke** [comment]
papasmacbookpro:f-engrave smorris$ find . -type d -name .git -prune -o -print0|xargs -0 ls -ltrd
-rwxr-xr-x@  1 smorris  staff   67208 Oct  7  2017 ./dist/f-engrave.app/Contents/MacOS/f-engrave
-rw-r--r--@  1 smorris  staff     792 Jun 25 20:47 ./.gitignore
-rw-r--r--@  1 smorris  staff     539 Jun 25 20:47 ./INSTALL.txt
-rw-r--r--@  1 smorris  staff    6191 Jun 25 20:47 ./README.md
-rw-r--r--@  1 smorris  staff     802 Jun 25 20:47 ./TTF2CXF_STREAM/INSTALL.txt
-rw-r--r--@  1 smorris  staff     818 Jun 25 20:47 ./TTF2CXF_STREAM/Makefile
-rw-r--r--@  1 smorris  staff   18092 Jun 25 20:47 ./TTF2CXF_STREAM/gpl-2.0.txt
-rw-r--r--@  1 smorris  staff   11495 Jun 25 20:47 ./TTF2CXF_STREAM/ttf2cxf_stream.cpp
-rw-r--r--@  1 smorris  staff     339 Jun 25 20:47 ./build.bat
-rwxr-xr-x@  1 smorris  staff    1764 Jun 25 20:47 ./build.sh
-rwxr-xr-x@  1 smorris  staff  412480 Jun 25 20:47 ./f-engrave.py
-rw-r--r--@  1 smorris  staff     383 Jun 25 20:47 ./fengrave.icns
-rw-r--r--@  1 smorris  staff   22438 Jun 25 20:47 ./fengrave.ico
-rw-r--r--@  1 smorris  staff   35821 Jun 25 20:47 ./gpl-3.0.txt
-rwxr-xr-x@  1 smorris  staff    1782 Jun 25 20:47 ./macOS-update.sh
-rw-r--r--@  1 smorris  staff   15340 Jun 25 20:47 ./macOS.patch
-rw-r--r--@  1 smorris  staff     837 Jun 25 20:47 ./py2exe_setup.py
-rw-r--r--@  1 smorris  staff    1415 Jun 25 20:47 ./setup.py
drwxr-xr-x@  7 smorris  staff     224 Jun 25 20:51 ./TTF2CXF_STREAM
-rwxr-xr-x@  1 smorris  staff   30928 Jun 25 20:51 ./TTF2CXF_STREAM/ttf2cxf_stream
drwxr-xr-x@  3 smorris  staff      96 Jun 25 20:51 ./dist
drwxr-xr-x@  3 smorris  staff      96 Jun 25 20:51 ./dist/f-engrave.app
drwxr-xr-x@  2 smorris  staff      64 Jun 25 20:51 ./dist/f-engrave.app/Contents/Resources
-rw-r--r--@  1 smorris  staff    2182 Jun 25 20:51 ./dist/f-engrave.app/Contents/Info.plist
drwxr-xr-x@  6 smorris  staff     192 Jun 25 20:51 ./dist/f-engrave.app/Contents
-rw-r--r--@  1 smorris  staff       8 Jun 25 20:51 ./dist/f-engrave.app/Contents/PkgInfo
drwxr-xr-x@  3 smorris  staff      96 Jun 25 20:51 ./dist/f-engrave.app/Contents/MacOS
drwxr-xr-x@ 18 smorris  staff     576 Jun 25 20:51 .

**Comment by stephenhouser** [comment]
Looks like `ttf2cxf_stream` sub-project did not get built. 

You can check by trying to cd to the `TTF2CXF_STREAM` directory and running `make osx` therein.

**Comment by zencuke** [comment]
As you can see from the directory listing above ./TTF2CXF_STREAM/ttf2cxf_stream did get built. That is what make osx does. It just didn't get copied to the app. Isn't that the responsibility of py2app?

Do I need to do the recovery mode/permission change dance mentioned in build.sh? I was following the instructions in README.md which said "run `build.sh`.  This will create..." When this step failed I stopped reading and tried to address the fail before continuing to the next step. Now that I have read build.sh and read on in README.md I see that the following text isn't the "next step." It seems to 
have information you need before running build.sh. You might consider rewriting this sequence in the readme to clarify. It should really say something like "clear up these dependancies THEN run build.sh." Or "Try build.sh. If it fails..."

**Comment by stephenhouser** [comment]
Oh, sorry, the listing wasn't in the order I expected as I read it. Yes `py2app` should have copied it. You should go through the "change dance" mentioned, but I don't think that's the problem. Typically the `csrutil` is needed to make `py2app` work. It looks like that already worked for you.

You are correct, it should be in the README, not after things have already failed on you.

Looking at the problem. Having the same failure when I try to build with 10.13.5

Pull requests to fix things are always welcome.

**Comment by stephenhouser** [comment]
Doing the "change dance" solved what appeared to be the same build problem on my system. Please let me know if it solves it for you as well.

I will update `build.sh` to fail properly and add some notes to the README.

**Comment by zencuke** [comment]
thanks. It is always good when an issue can be duplicated. I always suspect operator error and am afraid of wasting developer time with a bogus issue. I  guess I should learn git well enough to generate a pull request since I had this one mostly debugged. ;-) I may not get back to it untill the weekend but I'll let you know. Since you saw the identical symptoms and tested the fix the odds are greater than 99% that it will fix my problem as well so if you want to close it now I'm down with that.

**Comment by stephenhouser** [comment]
Doing the dance just fixed my build. Pushing up some changes after I spellcheck.

**Comment by stephenhouser** [comment]
Closed with commit https://github.com/stephenhouser/f-engrave/commit/992e9f3bbd568be41d3198f6424b5aed99fe9fdf

**Comment by zencuke** [comment]
Note: sorry to confuse things with non standard  ls order. I sorted by time to separate original install files from files which came from running build.sh.

**Comment by stephenhouser** [comment]
No worries.
